### ISSUE TITLE
Embedded/inline image autoload problem

### ISSUE THREAD

**Issue by bsibsi** [Airmail/Airmail_Public#569] opened 2014-04-14 22:24 UTC
When autoload remote images is turned off, the local images (embedded inline images inside message body, linked with img src="cid:imgname") didn't show up as well. I can only get them loaded and displayed by pressing CMD-J. These images should be loaded and shown automatically, without any user interaction.

**Comment by jeffsenn** [comment] 2015-06-05 13:24
Me too!  Please fix this!!

**Comment by jeffsenn** [comment] 2015-06-05 13:25
Note: this is a duplicate of #356

**Closed** 2015-08-11 22:08 UTC
